### ISSUE TITLE
IE9 Support

### ISSUE THREAD

**Issue by martincastell** [slimjack/IWC#1]
Hello, I've been looking for a library to do cross tab communication, I've looked at: Intercom, DuelJS, crosstab, page-bus and IWC. 

I really like IWC but no IE9 support is a deal breaker for me, could you please talk about what's missing on IE9 or what needs to be implemented in order to support it?

**Comment by slimjack** [comment]
Hello. Thanks for your comment. It's nice to know that you like it.
IE9 doesn't provide key and value of changed `localStorage` item in `onstorage` event. I didn't manage to encapsulate a fix in `SJ.localStorage`. So, all subscribers shouldn't rely on key/value in event handlers. This requires to revise all IWC functionality. IE is an evil.
I also have requirement in my project to support IE9. So, if you can wait, I'll try to implement IE9 support in one week.

**Comment by martincastell** [comment]
That would be great, thank you very much.

**Comment by slimjack** [comment]
I've added IE9 support. In case of any problems, please, notify me.
