### ISSUE TITLE
Observable.un is not removing the eventListener

### ISSUE THREAD

**Issue by martincastell** [slimjack/IWC#2]
The problem is in the Observable module, when getting the listener, it's using eventListeners[i].listenerFn which doesn't exist. 

```
if (eventListeners[i].listenerFn === listenerFn && eventListeners[i].scope === scope) {
```

The fix is to change eventListeners[i].listenerFn for eventListeners[i].fn.

**Comment by martincastell** [comment]
Pull Request: https://github.com/slimjack/IWC/pull/3

**Comment by slimjack** [comment]
Merged. Thanks.
