### ISSUE TITLE
Incorrect windowOn call

### ISSUE THREAD

**Issue by brian428** [slimjack/IWC#7]
The call to `windowOn()` in line 24 of Lock.js is incorrect (https://github.com/slimjack/IWC/blob/c9f6175c705b05358e112d4fe3f4318c47541149/src/iwc/Lock.js#L24). It passes `window` as the first argument to `windowOn()`, but `windowOn()` expects only arguments for event name and handler function.

I believe it just needs to be changed to: `SJ.windowOn('unload', onWindowUnload);`

**Comment by slimjack** [comment]
You are right. Thank you.
