### ISSUE TITLE
TypeError: activeLocks[i] is undefined

### ISSUE THREAD

**Issue by ferrean** [slimjack/IWC#9]
Steps to reproduce the problem:
1. Open webpage
2. Refresh webpage

In Firefox I get error:
"TypeError: activeLocks[i] is undefined"

In Chrome it is visible for a very short moment:
"Uncaught TypeError: Cannot read property 'release' of undefined"

**Comment by gruns** [comment]
This error occurs in the latest Chrome v65.0.3325.181, too.

To reproduce:

  1. Load https://jsfiddle.net/zp1vzz9d/1/.

  2. Refresh the page. On unload, the error occurs. Enable `Preserve log` in
     Chrome devtools to see the error.

https://i.gyazo.com/87958a8ff387ba093ff9148b11679e3f.png

**Comment by gruns** [comment]
PR https://github.com/slimjack/IWC/pull/11 resolves this issue.

@slimjack:

  1) Is there an automated way to run all the tests in `tests/`? Or do you just
     open them in the browser and test them by hand?

  2) How would you like me to bundle iwc-all.js and iwc-all.min.js from
     bundleconfig.json without ASP.NET? I don't have a Windows machine.

     Alternatively, would you merge a pull request that adds WebPack
     (https://webpack.js.org/) bundling + minification support? If so, I'll
     submit that in a new PR.

**Comment by slimjack** [comment]
@gruns 
1. For now I run tests in browser. I think it can be automated. But I don't have a time to do it.
2. Go ahead. Let's add WebPack.

Thank you for contribution!

**Comment by jeanie77** [comment]
Bundles updated with pull request https://github.com/slimjack/IWC/pull/14.
